[coreview] read json data from html page
manga-download/hakuneko pull request #2094
Opened 2020-07-20 15:17 UTC by hyww

shonenjumpplus.com returns 404 on `${chapter id}.json` requests. read json data from html pages instead.

Sorry I am not sure if this works for all coreview based sites. Maybe this fix should be applied only to shonenjumpplus.

2020-07-20 17:07 UTC, 27136773 requested changes
Looks like a good addition, unfortunately i cannot approve this without a confirmation of manual testing for each affected connector.
It would be sad if this fixes ShonenJump+, but breaks all other 8 websites.
The second approach would be the mentioned overwrite of `_getPages()` in `ShonenJumpPlus` only.

Sample Checklist for manual Testing (See also https://github.com/manga-download/hakuneko/pull/2086#issue-451976901):

- [ ] ShonenJump+
Sample: https://shonenjumpplus.com/episode/13933686331681119000
- [ ] TonariNoYoungJump
Sample: https://tonarinoyj.jp/episode/13933686331675753623

...

----
**CoreView based websites**

![image](https://user-images.githubusercontent.com/27136773/87964952-44c9ea80-cabb-11ea-8832-33d6a0fadd2c.png)

2020-07-22 05:14 UTC, ronny1982 commented
Probably related #2096

2020-07-22 20:24 UTC, newaccforhc commented
@ronny1982 I've tested this with each and every coreview connector supported by HakuNeko (The list in your Screenshot) and it works... You can approve it.

2020-07-23 19:36 UTC, 27136773 approved these changes
Functionality confirmed by @newaccforhc

2020-07-23 19:37 UTC, merged