add Aloalivn
manga-download/hakuneko pull request #2700
Opened 2020-11-29 08:57 UTC by Robonau

mentioned by sheep on discord

2020-11-30 21:02 UTC, Sheepux requested changes

2020-11-30 21:02 UTC, Sheepux commented on src/web/mjs/connectors/Aloalivn.mjs
> +        this.queryPages = 'li.blocks-gallery-item source'
Missing semicolon

2020-12-09 10:18 UTC, ronny1982 requested changes
Required to fix lint errors

2020-12-09 10:18 UTC, 27136773 commented on src/web/mjs/connectors/Aloalivn.mjs
> +        this.url = 'https://aloalivn.com/';
May remove trailing slash

2020-12-10 08:28 UTC, ronny1982 approved these changes
Looks good

2020-12-14 08:50 UTC, ronny1982 commented
@Sheepux may unblock PR if changes are sufficient

2020-12-14 08:52 UTC, Sheepux approved these changes

2020-12-14 08:53 UTC, merged

2020-12-16 09:49 UTC, ronny1982 commented
References: dazedcat19/FMD2#214