Changed the Loading Animation at startup
manga-download/hakuneko pull request #3231
Opened 2021-03-23 19:02 UTC by ef1500

<img width="363" alt="Updater" src="https://user-images.githubusercontent.com/45581646/112202965-9e009580-8bd7-11eb-98b1-abc67ccf2747.PNG">

2021-03-23 20:24 UTC, ronny1982 commented
Avoid adding user specific configuration files in `.vs/` to the repository

2021-03-23 20:47 UTC, ronny1982 requested changes

2021-03-23 20:47 UTC, ronny1982 commented on package.json
> +    "babel-core": "^6.26.3",
Do not add unused dependency

2021-03-23 20:47 UTC, ronny1982 commented on package.json
> +    "react": "^17.0.1",
Do not add unused dependency

2021-03-23 20:47 UTC, ronny1982 commented on package.json
> +    "react-dom": "^17.0.1",
Do not add unused dependency

2021-03-23 20:47 UTC, ronny1982 commented on src/app/CommandlineArgumentExtractor.js
> +            applicationCubeURL:           this._get('--cubeloader-url'),
The command line flags are more targeting developers, i don't think it is necessary to make the loading page configurable

2021-03-23 20:47 UTC, ronny1982 commented on src/app/App.js
> +            await this._electron.loadURL(this._configuration.applicationCubeURL);
I suggest to always load `hakuneko://cache/loader.html` instead of making it configurable

2021-03-23 20:47 UTC, ronny1982 commented on src/app/ElectronBootstrap.js
>          this._window = new electron.BrowserWindow({
Keep the default width/height/title until there is a request by users to change them

2021-03-23 20:47 UTC, ronny1982 commented on src/app/ElectronBootstrap.js
> +            titlebarstyle: 'hidden', //oooo borderless window!
Windows is already set to borderless in a different place.

2021-03-23 20:47 UTC, ronny1982 commented on src/app/ElectronBootstrap.js
> +            backgroundColor: '#202225', //The Color change was killing me going into dark mode
If the background color should be changed i suggest a more neutral grey shade, that is independent of any user selected theme

2021-03-23 20:47 UTC, ronny1982 commented on src/app/ElectronBootstrap.js
> +            show: false, //No Idea what the hell this does, I'll leave it alone
Do not add personal comments

2021-03-23 20:47 UTC, ronny1982 commented on src/web/lib/hakuneko/frontend@classic-dark/cubeloader.html
> +</div>
This file seems not to be used, delete unused file

2021-03-23 21:46 UTC, ef1500 commented on src/app/ElectronBootstrap.js
> +            show: false, //No Idea what the hell this does, I'll leave it alone
Sorry about that, won't happen again.

2021-03-24 00:32 UTC, ronny1982 requested changes

2021-03-24 00:32 UTC, ronny1982 commented on package.json
> +    "electron": "^7.3.3",
Should keep `8.3.4` if there is no compatibility issue with the new loading screen

2021-03-24 00:32 UTC, ronny1982 commented on src/app/Configuration.js
>          let applicationExecutableDirectory = path.dirname(electron.app.getPath('exe'));
Can revert changes in this file since the `cubeloader.html` is now statically applied in `App.js`

2021-03-24 06:42 UTC, ronny1982 reviewed
Ready for manual verification by reviewer

2021-03-27 18:39 UTC, ronny1982 commented
I tested the changes locally and it worked so far.
However, the loading screen flashes in an instant (when no updates are installed) and therefore no animation could be seen at all. I'm afraid the user might be confused about the short flashing image without enough time to see what it was.

Also the color change from dark grey to the light theme (yes i'm guilty of being light theme user) is very steep and uncomfortable.

Furthermore, the change requires an updated electron client (nightly build) to be fully working. It is very likely that no new clients based on electron will be released.

2021-03-27 18:40 UTC, ronny1982 commented
I recommend to take a look into the [HaruNeko prototype](https://github.com/manga-download/haruneko/blob/master/src/splash.html) which will probably be the successor of HakuNeko and contribute the splash screen solution for this project.

2021-03-28 14:02 UTC, Sheepux commented
Note: also in haruneko it's more than just an updater it's also waiting for the UI to be ready (when UI is sending a ready signal) to display the main window and therefore you won't be getting the second "waiting time" you can see in the video

2021-04-01 17:43 UTC, ronny1982 commented
Going to close this for 6.1.7 / Nightly since chances are slim that it would make its way to the users...

2021-04-01 17:43 UTC, closed without merging