Corrected ReaperScansFr
manga-download/hakuneko pull request #4597
Opened 2022-04-23 14:14 UTC by Oneloutre

**ReaperScansFr** moved to a new template / new URL so here is the patch.

2022-04-23 17:53 UTC, Sheepux requested changes

2022-04-23 17:53 UTC, Sheepux commented on src/web/mjs/connectors/ReaperScansFR.mjs
> -}
Missing closing brace

2022-04-23 23:03 UTC, Oneloutre commented
Yep, changed

2022-04-24 10:23 UTC, Sheepux commented on src/web/mjs/connectors/ReaperScansFR.mjs
> +export default class ReaperScans extends WordPressMadara {
do not change the class name, should be the same as the id and correlated to the name/label.

2022-04-24 10:28 UTC, Oneloutre commented
Yeah, excuse me X) i've made a mistake indeed; but now, it's fine.

2022-04-24 10:29 UTC, Sheepux approved these changes
/LGTM
(no problem, that's why review are here for)

2022-04-24 10:34 UTC, merged