add connector
manga-download/hakuneko pull request #5207
Opened 2022-12-07 09:21 UTC by akn19

- hinapyon
- tukangkomik ( Fixes https://github.com/manga-download/hakuneko/issues/4754 )
- lianscan
- duniakomik (gabutscan)
- mangaindoMe

2022-12-07 10:19 UTC, MikeZeDev commented
I see nothing wrong but i am fairly new here and i dont know the policy about renamed connectors.

2022-12-07 11:31 UTC, akn19 commented
[DISCORD] on 2022/02/10 gabutscan announced moving their website to a new domain for the main reason of optimization and leaving their old website.

it would be nice if the owner of this project added a contributing guide like [vscode](https://github.com/microsoft/vscode/blob/main/CONTRIBUTING.md) and many other open source projects.

sorry if my english is bad.

2022-12-07 12:45 UTC, Sheepux commented
you mean this ? https://github.com/manga-download/hakuneko/wiki

2022-12-07 12:54 UTC, MikeZeDev commented
So, basically when connector name or group name change its a bad idea to rename a file or change the id.

* You modify the existent connector and keep the id inside (so people dont lose cached manga lists and bookmarks). 
* Or you make a brand new one.

In this PR , classname is still "GabutScans" and does not match the filename btw. Make sure the class name matches the filename.

2022-12-08 04:57 UTC, akn19 commented
> * You modify the existent connector and keep the id inside (so people dont lose cached manga lists and bookmarks).
> * Or you make a brand new one.
> 
> In this PR , classname is still "GabutScans" and does not match the filename btw. Make sure the class name matches the filename.

done

2022-12-08 10:51 UTC, MikeZeDev commented on src/web/mjs/connectors/DoujinDesu.mjs
>          this.queryChaptersTitle = undefined;
If this variable is not used it should be deleted.

2022-12-08 11:08 UTC, MikeZeDev commented
I tested DoujinDesu manga/ecchi-na-fuushuu-ga-aru-kaso-shuuraku-no-ohanashi/ and i got some error 403 on pictures. Host need https://doujindesu.xxx as referer. 

To add referer for pictures you need to wrap images urls with this.createConnectorURI(pictureurl), override handleConnectorURI and using it to pass the good referer to the picture request
```
    async _handleConnectorURI(payload) {
        let request = new Request(payload this.requestOptions);
        request.headers.set('x-referer', this.url);
        let response = await fetch(request);
        let data = await response.blob();
        data = await this._blobToBuffer(data);
        this._applyRealMime(data);
        return data;
    }
```

2022-12-08 11:37 UTC, MikeZeDev requested changes

2022-12-08 11:37 UTC, MikeZeDev commented on src/web/mjs/connectors/DoujinDesu.mjs
>          this.queryChaptersTitle = undefined;
Maybe you should delete queryChaptersTitle if its not used?

2022-12-08 11:37 UTC, MikeZeDev commented on src/web/mjs/connectors/LianScans.mjs
> +        let data = await this.fetchDOM(request, 'div.listupd div.bs div.bsx > a');
Why not using this.queryMangas which you defined?

2022-12-15 10:08 UTC, akn19 commented on src/web/mjs/connectors/DoujinDesu.mjs
>          this.queryChaptersTitle = undefined;
> Maybe you should delete queryChaptersTitle if its not used?

chapter list is empty if i delete it

2022-12-15 10:12 UTC, MikeZeDev commented on src/web/mjs/connectors/DoujinDesu.mjs
>          this.queryChaptersTitle = undefined;
Ok its a template thing i see

2022-12-15 10:14 UTC, MikeZeDev commented on src/web/mjs/connectors/LianScans.mjs
> +        let data = await this.fetchDOM(request, 'div.listupd div.bs div.bsx > a');
there is this to solve. 
        let data = await this.fetchDOM(request, 'div.listupd div.bs div.bsx > a');
could be replaced by  
        let data = await this.fetchDOM(request, this.queryMangas);

2022-12-15 10:16 UTC, akn19 commented on src/web/mjs/connectors/LianScans.mjs
> +        let data = await this.fetchDOM(request, 'div.listupd div.bs div.bsx > a');
Done

2022-12-15 11:19 UTC, akn19 commented
> I tested DoujinDesu manga/ecchi-na-fuushuu-ga-aru-kaso-shuuraku-no-ohanashi/ and i got some error 403 on pictures. Host need https://doujindesu.xxx as referer.
> 
> To add referer for pictures you need to wrap images urls with this.createConnectorURI(pictureurl), override handleConnectorURI and using it to pass the good referer to the picture request
> 
> ```
>     async _handleConnectorURI(payload) {
>         let request = new Request(payload, this.requestOptions);
>         request.headers.set('x-referer', this.url);
>         let response = await fetch(request);
>         let data = await response.blob();
>         data = await this._blobToBuffer(data);
>         this._applyRealMime(data);
>         return data;
>     }
> ```

this code not work for me

```
:authority: pixdesu.art
:method: GET
:path: /storage/drive/n704ZRlEl35xjVwncoPWDSwTB3SXCN/JoCxHZFEuJQGPwULU8DPczCk4uRl19/2ShcaY7dBV0TmiA5eBCI3DdIPZH5OT/bjtS30eYKpkNH9OTCoBGQFfoyEngEc.webp
:scheme: https
accept: image/webp,image/apng,image/*,*/*
accept-encoding: gzip, deflate, br
accept-language: en-US
sec-ch-ua: 
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.32.4805.947 Safari/537.36
```
---
use `this.requestOptions.headers.set('x-referer', this.url);`

```
:authority: pixdesu.art
:method: GET
:path: /storage/drive/n704ZRlEl35xjVwncoPWDSwTB3SXCN/JoCxHZFEuJQGPwULU8DPczCk4uRl19/2ShcaY7dBV0TmiA5eBCI3DdIPZH5OT/25F9Lof6eAvSjIe98UeLyWWR6e9oWG.webp
:scheme: https
accept: image/webp,image/apng,image/*,*/*
accept-encoding: gzip, deflate, br
accept-language: en-US
referer: https://212.32.226.234
sec-ch-ua: 
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.28.1389.132 Safari/537.36
```

2022-12-15 12:46 UTC, MikeZeDev commented
Because you did half of the job :).  "HandleConnectorURI' isnt used without a "connectorURI", which i a special way to wrap images links, so hakuneko know there are special things to do, and then use 'HandleConnectorURI'

Like i said : 

>to add referer for pictures you need to wrap images urls with this.createConnectorURI(pictureurl)

Images urls are returned in _getpages. You have to copy getpages from the template WordPressMangastream.mjs, and make is so it returns this.createConnectorURI(pictureurl) array .

Exemple of use : https://github.com/manga-download/hakuneko/pull/5237/files **(dont copy it)**

2022-12-19 10:02 UTC, MikeZeDev approved these changes

2022-12-19 10:05 UTC, merged