Add new website cosmicscansID, komikbree, rrscans, moonscans
manga-download/hakuneko pull request #5471
Opened 2023-02-13 17:45 UTC by KazielZoe

Add new website cosmicscans.id, komikbree.xyz, rrscans.my.id, moonscans.xyz

2023-02-14 11:05 UTC, MikeZeDev commented on src/web/mjs/connectors/CosmicScansID.mjs
> +export default class CosmicScans extends WordPressMangastream {
* Class must match filename
* This class is already used by english cosmic scans btw

2023-02-14 11:06 UTC, MikeZeDev commented on src/web/mjs/connectors/KomikBree.mjs
> +export default class Aiinscan extends WordPressMadara {
* Class must match filename

2023-02-14 11:06 UTC, MikeZeDev commented on src/web/mjs/connectors/MoonScans.mjs
> +export default class CosmicScans extends WordPressMangastream {
* Class must match filename

2023-02-14 11:11 UTC, MikeZeDev requested changes
* Class names fixes required
* Please provide 4 icons for the 4 websites.

2023-02-14 11:11 UTC, MikeZeDev commented on src/web/mjs/connectors/RRScans.mjs
> +export default class CosmicScans extends WordPressMangastream {
* Class must match filename and be unique

2023-02-18 08:36 UTC, MikeZeDev commented
Icons files are way to big. Ideally they should be png, < 16kb and dimension max 96x96 px

2023-02-18 10:27 UTC, MikeZeDev commented
Cosmics Scans pictures are behind Cloudflare , its pointless to add this website

![image](https://user-images.githubusercontent.com/10671518/219855441-b03e5def-30cc-4ac6-9038-b8e59c34643c.png)

2023-02-18 10:29 UTC, MikeZeDev commented
Many komikbree mangas have 'Bahasa indonesia' in name, You may want to get rid of that

2023-04-07 11:33 UTC, ronny1982 commented
No response since more than the defined `6 weeks` after review feedback, is this still worked on?

2023-04-10 12:36 UTC, closed without merging