Add BentoManga connector
manga-download/hakuneko pull request #5669
Opened 2023-04-10 16:58 UTC by TristanWasTaken

I ~~stole~~ borrowed the [connector](https://github.com/manga-download/hakuneko/issues/4513#issuecomment-1086654730) from @courli79 and fixed the out of date `_getChapters` function.
This solves #5114 and kinda solves #4513

The PR is marked as draft since, as it turns out, BentoManga now has an api
Example: https://bentomanga.com/manga/poison-dragon-the-legend-of-an-asura/chapter/56
- https://bentomanga.com/api/?id=237487&type=chapter
- https://bentomanga.com/api/?id=10202&type=manga

The connector url needs improvement too since BentoManga has a `www` subdomain too
Example:
- https://bentomanga.com/manga/poison-dragon-the-legend-of-an-asura
- https://www.bentomanga.com/manga/poison-dragon-the-legend-of-an-asura

There is also the chapter page problem. BentoManga gets more chapters by requesting the list html in a similar way as the chapter api requests.
example: https://bentomanga.com/manga/everyone-else-is-a-returnee
- https://bentomanga.com/manga/everyone-else-is-a-returnee?order=desc&limit=1
- https://bentomanga.com/manga/everyone-else-is-a-returnee?order=desc&limit=2

**Tasks:**
- [x] implement api
- [x] add url regex
- [x] solve _getChapter page limit

Fixes https://github.com/manga-download/hakuneko/issues/5114
Fixes https://github.com/manga-download/hakuneko/issues/4513 (Japanread is now bentomanga, its redirecting)

2023-04-10 17:38 UTC, MikeZeDev requested changes
* Manga list should be multipages like on the website
* Manga list could be fetched using api to reduce server load
* Must fix clipboard selector
* You said yourself there are manga with www and without www in url so you must override `canHandleUri` and use a good regex that match both cases

2023-04-10 17:38 UTC, MikeZeDev commented on src/web/mjs/connectors/BentoManga.mjs
> +        let data = await this.fetchDOM(request, 'h1');
Way too lax CSS selector. You must make sure it will be unique. 

``` div.component-manga-title_main h1 ``` is a better candidate

2023-04-10 17:38 UTC, MikeZeDev commented on src/web/mjs/connectors/BentoManga.mjs
> +        let request = new Request(this.url + '/manga_list', this.requestOptions);
This method is fine by itself but Bentomanga got more than 1k manga pages. 
Suggestion to use _getmangas and _getMangasFromPage from [Sample.mjs](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/templates/%40Samples.mjs)

If you want to be efficient, you can get JSON manga with html data inside by calling 
https://bentomanga.com/manga_list?limit=X&cb=Y . 

X being page number-1, cb being the timestamp from when you call the page.
This request must get a special header, with name "X-Requested-With" and value "XMLHttpRequest". 

Then you get some html in the json ("mangas")

```
	<div class="div-manga_cover">
		<a href="https://bentomanga.com/manga/maseki-gurume-mamono-no-chikara-o-tabeta-ore-wa-saikyou" class="component-manga-cover">
			<img alt="couverture manga" src="https://bentomanga.com/media/cache/manga_medium/images/mangas/cover/5e47469782828797082475.jpg">
				<span class="div-manga_cover-title">Maseki Gurume: Mamono no Chikara o Tabeta Ore wa Saikyou!</span>
		</a>
		<span class="badge-chapterCount mobile-adapt">0/29</span>
	</div>
```

There are plenty of sample about how to do that in other connectors.


        request.headers.set('X-Requested-With', 'XMLHttpRequest'); 
        const data = await this.fetchJSON(request);
        const dom =  this.createDOM( data.mangas ); //json got html  data in "mangas"
        const mangaNode = dom.querySelector('div.div-manga_cover a');
        return mangaNode.map(element => {
            return {
                id: this.getRootRelativeOrAbsoluteLink(element, this.url),
                title: element.querySelector('span.div-manga_cover-title').textContent.trim()
            };
        });

2023-04-10 17:38 UTC, MikeZeDev commented on src/web/mjs/connectors/BentoManga.mjs
> +                title: element.querySelector('span.chapter_volume').innerText.trim() + ' ' + element.querySelector('span.chapter_title').innerText.trim(),
Are there other elements than chapter_volume and chapter_title ? cant we just get element.text.trim() as title? 
Not a big deal tbh

2023-04-10 17:38 UTC, MikeZeDev commented on src/web/mjs/connectors/BentoManga.mjs
> +                    headers: {"a":"Math.random().toString(16)"}
Apparently, no need for "a" in custom headers. But you will need ('X-Requested-With', 'XMLHttpRequest') like before; 

``` headers : { 'X-Requested-With' : 'XMLHttpRequest' } ```

2023-04-10 18:55 UTC, TristanWasTaken commented on src/web/mjs/connectors/BentoManga.mjs
> +                title: element.querySelector('span.chapter_volume').innerText.trim() + ' ' + element.querySelector('span.chapter_title').innerText.trim(),
> Are there other elements than chapter_volume and chapter_title

there are no other span elements in that the `component-chapter-title` div

2023-04-10 19:15 UTC, TristanWasTaken commented on src/web/mjs/connectors/BentoManga.mjs
> +                title: element.querySelector('span.chapter_volume').innerText.trim() + ' ' + element.querySelector('span.chapter_title').innerText.trim(),
> cant we just get element.text.trim() as title? Not a big deal tbh

possible, but then there is a missing white space between the chapter number and the title
e.g. https://bentomanga.com/manga/shingeki-no-kyojin-couleur
before: `Vol.27 Chapitre 107 Une invitée de marque`
after `element.text.trim(),`: `Vol.27 Chapitre 107Une invitée de marque`

2023-04-11 07:45 UTC, MikeZeDev commented
I think you are wasting your time because you said Cloudflare blocked you. No point adding a connector that theorically works id no one can use it ;-;

2023-04-11 14:08 UTC, TristanWasTaken commented
> I think you are wasting your time because you said Cloudflare blocked you

I didn't. It blocked 1.1.1.1, I just had to disable it.
I do have a problem with completely different html responses than in my browser tho

2023-04-11 18:38 UTC, MikeZeDev commented
Apparently no more cloudflare, or at least everything is passing o/

2023-04-11 18:44 UTC, MikeZeDev approved these changes

2023-04-12 09:07 UTC, merged

2023-11-19 09:57 UTC, ronny1982 commented
[Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27bentomanga%27&type=code)