add astral-manga connector
manga-download/hakuneko pull request #5680
Opened 2023-04-13 15:20 UTC by Neths

2023-04-13 21:13 UTC, MikeZeDev commented
Need to provide icon

2023-04-13 21:14 UTC, MikeZeDev commented on src/web/mjs/connectors/AstralManga.mjs
> +        this.url = 'https://astral-manga.fr/';
Remove leading /

2023-04-13 21:16 UTC, MikeZeDev requested changes
Minor changes required
* add icon
* Fix url

2023-04-14 15:48 UTC, Neths commented
fix minor changes

2023-04-14 17:03 UTC, MikeZeDev approved these changes

2023-04-14 17:03 UTC, merged

2023-11-19 09:56 UTC, ronny1982 commented
[Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27astralmanga%27&type=code)

2023-11-20 12:12 UTC, MikeZeDev commented
Added to Haruneko https://github.com/manga-download/haruneko/pull/344