Karatcam Scans
manga-download/hakuneko pull request #5853
Opened 2023-05-29 17:13 UTC by TristanWasTaken

https://karatcam-scans.fr

2023-05-29 17:39 UTC, MikeZeDev requested changes
* Maybe add the "scanlation" tag :)
* Remove the useless _getChaptersAjaxOld, it works anyway

2023-05-29 17:42 UTC, TristanWasTaken commented
> * scanlation

this one is new :thinking:

2023-05-29 17:45 UTC, MikeZeDev approved these changes

2023-05-29 17:46 UTC, merged

2023-11-19 09:37 UTC, ronny1982 commented
[Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27karatcamscans%27&type=code)