LegacyScans: change to Mangastream
manga-download/hakuneko pull request #5944
Opened 2023-06-24 03:51 UTC by TristanWasTaken

[Legacyscans](https://legacy-scans.com) temporarily rebranded to [flamescans.fr](https://mangadex.org/group/0f82ec30-3b70-4870-b57c-5ebda3f5c770) but are now back with flamescans mangastream theme.

I can't test it though since they're using cloudflare. But I copied the code from the flamescans.fr connector, so everything *should* work out of the box.

2023-06-24 03:56 UTC, TristanWasTaken commented
also #4972 would have to be updated
> legacyscans : moved to flamescanfr (which is already a connector)

2023-06-24 08:33 UTC, MikeZeDev commented
Sorry i ended up editing you message instead if answering :/
But yeah, i was mentioning https://github.com/manga-download/hakuneko/issues/4972

2023-06-24 08:53 UTC, MikeZeDev commented
Tried it. 

* no need for this.queryMangas.
* And i cant get pictures, i ma checking why

2023-06-24 09:08 UTC, MikeZeDev commented
Suggestions  : 

* Remove this.queryMangas
* add ```  this.requestOptions.headers.set('x-referer', this.url); ``` to the constructor;
* override _getpages so the referer we added is effective

``` 
    async _getPages(chapter) {
        return (await super._getPages(chapter)).map(page => this.createConnectorURI(page));
    }

```

2023-06-24 09:10 UTC, MikeZeDev requested changes
Suggestions  : 

* Remove this.queryMangas
* add ```  this.requestOptions.headers.set('x-referer', this.url); ``` to the constructor;
* override _getpages so the referer we added is effective

``` 
    async _getPages(chapter) {
        return (await super._getPages(chapter)).map(page => this.createConnectorURI(page));
    }

```

2023-06-24 18:41 UTC, ronny1982 approved these changes

2023-06-24 19:56 UTC, MikeZeDev commented
@ronny1982 I was able to test this. And i think i was not wrong asking for modifications, ie if you manage to bypass Cloudflare you still need the referer for pictures. Thanks for the approving boss, but i think its a bit hasty .

Should i not care since its CF plagued anyway?

2023-06-24 22:16 UTC, TristanWasTaken commented
@MikeZeDev I implemented the requested changes.
Though how does the Cloudflare bypass work? I still couldn't test the connector :/

2023-06-25 10:12 UTC, MikeZeDev approved these changes

2023-06-25 10:15 UTC, MikeZeDev commented
> @MikeZeDev I implemented the requested changes. Though how does the Cloudflare bypass work? I still couldn't test the connector :/

Changing the user agent for a particular one. However, we cant do that publicly as the agent will most likely be blacklisted, and its only giving mixed results (its not really reliable).

Thanks for the fix.

2023-06-25 10:16 UTC, merged

2023-06-25 19:08 UTC, TristanWasTaken commented
> Changing the user agent for a particular one. However, we cant do that publicly as the agent will most likely be blacklisted, and its only giving mixed results (its not really reliable).

so pretty much what I told you weeks ago that it works when I change the ua with a mitm proxy :smile: