feat(GalaxyAction): create connector
manga-download/hakuneko pull request #6290
Opened 2023-10-04 13:18 UTC by TristanWasTaken

https://galaxyaction.site/

2023-10-04 17:06 UTC, MikeZeDev requested changes
If redirect to flixscans, and flixscans use an api and its not mangastream

2023-10-05 21:12 UTC, ronny1982 commented on src/web/mjs/connectors/GalaxyManga.mjs
> +                title: chapter.title ? `${chapter.name} ${chapter.title.trim()}` : chapter.name
May be shortened to `title: `${chapter.name} ${chapter.title || ''}`.trim()`

2023-10-05 21:14 UTC, ronny1982 approved these changes

2023-10-05 21:50 UTC, TristanWasTaken commented
I just wrote with the site operator and he said that multiple scan groups will post to the site.
From what I see in the api manga response, each group would "own" a title like on bato.to
should the group name be attached to the manga name in the format `<manga> [<group>]` or it it fine since it's not multiple groups sharing one manga like on MangaDex?

2023-10-06 08:34 UTC, MikeZeDev approved these changes

2023-10-06 08:35 UTC, merged