Update CeriseScans.mjs
manga-download/hakuneko pull request #6312
Opened 2023-10-12 04:39 UTC by EliseuPinkoski

2023-10-12 13:13 UTC, MikeZeDev requested changes
1) English please
2) Why create a PR "Create CeriseScans" then another "Update Cerise scans"
3) This website is already supported 

![image](https://github.com/manga-download/hakuneko/assets/10671518/b175c1bb-d875-46dd-bdc5-c9ba5171187d)

2023-10-13 00:06 UTC, EliseuPinkoski commented
mjs is configured for novel and not for comic.

> Message ID: ***@***.***
> com>
>

2023-10-13 07:27 UTC, MikeZeDev commented
> mjs is configured for novel and not for comic.
> […](#)
> Message ID: ***@***.*** com>

WordPressMadaraNovel handles both.

2023-10-13 15:50 UTC, EliseuPinkoski commented
all works that are not new receive this warning
[image: image.png]

Em sex., 13 de out. de 2023 às 04:28, MikeZeDev ***@***.***>
escreveu:

> mjs is configured for novel and not for comic.
> … <#m_-2316012510984982659_>
> Message ID: *@*.*** com>
>
> WordPressMadaraNovel handles both.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/manga-download/hakuneko/pull/6312#issuecomment-1761038310>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQPEHTTQKLRM3N7WMP2BCC3X7DUQHANCNFSM6AAAAAA5472CAY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-13 20:43 UTC, MikeZeDev commented
there is no image

2023-10-16 00:17 UTC, EliseuPinkoski commented
This website in question is mine, it has the images and everything is
correct but it doesn't work, it only works in the novels, but everything is
fine, thank you!


Em sex., 13 de out. de 2023 às 17:43, MikeZeDev ***@***.***>
escreveu:

> there is no image
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/manga-download/hakuneko/pull/6312#issuecomment-1762178897>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQPEHTR3ERS6ROSL7KQ4ZR3X7GRYJANCNFSM6AAAAAA5472CAY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-16 09:22 UTC, MikeZeDev commented
You made some good changes and some changes that will make it not working.

If you want it to work, trust me, and do the requested changes. If you dont do that nothing will be merged and PR will be closed.

Maybe we are lost in translation.

2023-10-21 09:11 UTC, MikeZeDev approved these changes

2023-10-21 09:11 UTC, MikeZeDev commented on src/web/mjs/connectors/CeriseScans.mjs
> +export default class Cerisescan extends WordPressMadara {
Class name must match file name, there is no reasons to change it.
Also keep MadaraNovel .

2023-10-21 09:11 UTC, MikeZeDev commented on src/web/mjs/connectors/CeriseScans.mjs
> +        super.id = 'CeriseScan';
Dont change id, NEVER. Also it must stay lowercase.

2023-10-21 09:11 UTC, MikeZeDev commented on src/web/mjs/connectors/CeriseScans.mjs
> +import WordPressMadara from './templates/WordPressMadara.mjs';
are you sure there is no more novels on the website? 

Edit : https://cerisescan.com/manga/100/cap-01/ 
Keep MadaraNovel

2023-10-21 09:29 UTC, merged

2023-10-21 16:45 UTC, EliseuPinkoski commented
now it's working perfectly,

I appreciate the changes.

Em sáb., 21 de out. de 2023 às 06:29, MikeZeDev ***@***.***>
escreveu:

> Merged #6312 <https://github.com/manga-download/hakuneko/pull/6312> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/manga-download/hakuneko/pull/6312#event-10730931302>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQPEHTVIEEUYJ4NOLPICXKTYAOIYXAVCNFSM6AAAAAA5472CA2VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJQG4ZTAOJTGEZTAMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>