add OremangaNet.mjs
manga-download/hakuneko pull request #6443
Opened 2023-11-18 16:46 UTC by YainuWan11

add file OremangaNet.mjs

2023-11-18 19:39 UTC, MikeZeDev requested changes
Nice. That said, we need an icon. Put a png file (64x64 px) without extension with name matching the connector id :  ``` src/web/img/connectors/oremanga ```

2023-11-18 19:39 UTC, MikeZeDev commented on src/web/mjs/connectors/OremangaNet.mjs
> +	this.path = '/manga-list'
tiny fix : its '/manga-list/', you miss a '/'  :p

2023-11-18 19:39 UTC, MikeZeDev commented on src/web/mjs/connectors/OremangaNet.mjs
> +async _getMangaFromURI(uri) {
You may want to fix indentation , Linter will yell :)

2023-11-18 19:43 UTC, MikeZeDev commented
I cant get pictures at all. Again, was it tested?

2023-11-19 06:02 UTC, YainuWan11 commented
Thank you,And I already added the icon.

2023-11-19 09:17 UTC, ronny1982 commented
Should we really allow to add new websites to HakuNeko?
It will get out of sync with HaruNeko...

2023-11-19 09:58 UTC, MikeZeDev commented
I think it would be reasonable to temporally freeze the addition of new websites in Hakuneko from contributors too.
I already stopped myself coding website for Hakuneko. I just fixes stuff for now.
By doing that we can concentrate on Haru.

On the other hand : 
* Its not like we have many submissions
* User submitted stuff is simple in general

We could make this one the last addition to Hakuneko for now?

2023-11-19 09:59 UTC, MikeZeDev commented
> Thank you,And I already added the icon.

yes but, i told you to respect the ID naming scheme. ID are all lowercase.

2023-11-19 10:25 UTC, ronny1982 commented
[Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27oremanga%27&type=code)

2023-11-20 10:47 UTC, MikeZeDev commented
No need to request more review if you dont change what is needed to change.

>yes but, i told you to respect the ID naming scheme. ID are all lowercase. See al other icons name? :D

2023-11-20 18:17 UTC, YainuWan11 commented
Already edited name the icon

2023-11-21 09:07 UTC, MikeZeDev approved these changes

2023-11-21 09:08 UTC, merged