feat(HeanCms, TempleScan, OmegaScans, YugenMangas, PerfScan): add HeanCms template
manga-download/hakuneko pull request #6510
Opened 2023-12-06 17:03 UTC by TristanWasTaken

- https://templescan.net (#5815)
- https://omegascans.org (#6364, #6368)
- https://yugenmangas.lat
- https://perf-scan.fr

[ReaperScansBR](https://github.com/manga-download/hakuneko/blob/ccebe4be37c8f9f5897816308aef8207cee9566b/src/web/mjs/connectors/ReaperScansBR.mjs)'s site is currently down, so I didn't change the connector.

conflicts #6368
fixes #5815
fixes #6364

2023-12-06 18:22 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +                    title: manga.title ? manga.title.trim() : null
Wait you mean, its possible to have a manga without title? Whats this sorcery? 
Is that normal? 

It thats really the case, remove them, we can work without title its dirty.

2023-12-06 18:23 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +        console.log(chapterList);
no need for comment in prod

2023-12-06 18:24 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +            throw new Error('Novel chapters are not supported!');
Novels should be supported. Idk how its for novels , regarding the API.

2023-12-06 18:26 UTC, TristanWasTaken commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +                    title: manga.title ? manga.title.trim() : null
yeah it could happen, after all there are no docs
e.g. hakuneko handled it very gracefully on timelessleaf

> It thats really the case, remove them, we can work without title its dirty.

what do you mean with "remove"? it's already null

2023-12-06 21:15 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +                    title: manga.title ? manga.title.trim() : null
Filter out the nulled titles before returning the array or remove the test. Its unlikely that manga title will be empty. I dont see anything relevant in timeless leaves btw

2023-12-07 09:49 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +	            let container = document.querySelector('div.container');
maybe put the selector as a class value too? 
and change the script so it can be "undefned"

2023-12-07 09:51 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +            // NOTE: The indonesian developer of statically.io (Frans Allen) seems to be affiliated with BacaKomik
useless commentary can be removed

2023-12-07 09:59 UTC, MikeZeDev requested changes
Seems good, minor changes required.

2023-12-07 10:55 UTC, MikeZeDev commented on src/web/mjs/connectors/PerfScan.mjs
> +        this.url = 'https://perf-scan.fr/';
Please remove trailing slash

2023-12-08 00:48 UTC, TristanWasTaken commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +            // NOTE: The indonesian developer of statically.io (Frans Allen) seems to be affiliated with BacaKomik
I mean you can keep the link for future reference but we dont need the explanation twice :p

2023-12-08 01:04 UTC, TristanWasTaken commented
I'll get to the other changes later. Busy until tomorrow ish.

2023-12-10 20:31 UTC, TristanWasTaken commented on src/web/mjs/connectors/templates/HeanCms.mjs
> +	            let container = document.querySelector('div.container');
Interesting. It didn't appear in my local VSC, but it did show in GitHub Desktop.
Weird character formatting issue, I guess.

2023-12-11 10:08 UTC, MikeZeDev approved these changes
I fixed a last minute bug :).

Thanks for this contribution, its appreciated :)

2023-12-11 10:08 UTC, merged

2024-01-06 11:45 UTC, Clouddark75 commented
Yugenmangas old episodes "images" from November 2022 to March 2023 
uses the API url to form the images example:
https://api.yugenmangas.net/chapter/nano-machine/captulo-1

"https://api.yugenmangas.net/uploads/series/nano-machine/0b632a1e-431f-4338-bc3f-07341de2b302/01.jpg"
So the connector is failing with these to rebuild the URL.

2024-01-06 12:54 UTC, MikeZeDev commented
> Yugenmangas old episodes "images" from November 2022 to March 2023 uses the API url to form the images example: https://api.yugenmangas.net/chapter/nano-machine/captulo-1
> 
> "https://api.yugenmangas.net/uploads/series/nano-machine/0b632a1e-431f-4338-bc3f-07341de2b302/01.jpg" So the connector is failing with these to rebuild the URL.

Nice catch. Please open an issue for that :).

2024-01-06 14:35 UTC, Clouddark75 commented
> > Yugenmangas old episodes "images" from November 2022 to March 2023 uses the API url to form the images example: https://api.yugenmangas.net/chapter/nano-machine/captulo-1
> > "https://api.yugenmangas.net/uploads/series/nano-machine/0b632a1e-431f-4338-bc3f-07341de2b302/01.jpg" So the connector is failing with these to rebuild the URL.
> 
> Nice catch. Please open an issue for that :).

Done!
https://github.com/manga-download/hakuneko/issues/6657

I hope you guys have a great day!