add connector sakuranovel
manga-download/hakuneko pull request #6964
Opened 2024-04-13 16:38 UTC by akn19

2024-04-14 12:58 UTC, MikeZeDev commented
How did i miss this dupe?

2024-04-14 13:23 UTC, MikeZeDev requested changes

2024-04-14 13:23 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +        this.novelContentQuery = 'div.asdasd';
I have the feeling that this selector is not good

2024-04-14 13:23 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +            this.adLinkDecrypt(element);
useless

2024-04-14 13:23 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +        this.novelContentQuery = 'div.asdasd';
![image](https://github.com/manga-download/hakuneko/assets/10671518/d3d67206-d49e-4312-a22b-1d25bdc0ede3)

2024-04-14 13:23 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +                title: title.replace(manga.title + ' – ', '').replace(/Bahasa Indonesia$/i, '').trim()
I ask myself why do they need to put the language everywhere.. More garbage, more and mooore garbage..
Anyway,  chapters still got manga title for some reasons according to the screenshot i took.

Did you test? Its enough to use super._getchapters() and then remove bahasa, EXACTLY like you did on monzee for mangas. No need for that complicated stuff.

2024-04-14 13:23 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +        return data.length > 0 ? this._getPagesNovel(request) : super._getPages(chapter);
If they have only novels its useless to check you can just call _getPagesNovel.

2024-04-14 13:24 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +        this.novelContentQuery = 'div.asdasd';
Please test your code before submitting, its not working.

2024-04-14 15:20 UTC, akn19 commented
the code I used previously came from the KolNovel connector.

Excessive use of the word "Bahasa Indonesia" is most likely aimed at SEO, because of the low literacy of our society, they will be more likely to visit websites with titles containing the word "Bahasa Indonesia" in search engines.

2024-04-14 15:21 UTC, akn19 commented
![gambar](https://github.com/manga-download/hakuneko/assets/86169232/f22bdd82-19cd-454e-b1b8-27e1e4ede8a6)

2024-04-14 17:36 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +        this.novelContentQuery = 'div.asdasd';
Well its better the thing is i wonder why i works on some novels and not on others, like i see in the screen.

🤔

2024-04-14 17:46 UTC, MikeZeDev requested changes
Minor changes required, and we must know why it doesnt work everywhere likz in the screen i posted

2024-04-14 17:46 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +                let container = document.querySelector('div.asdasd');
you made a constant for this, you could use it there :)

2024-04-14 17:46 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +        const mangas = await super._getChapters(manga);
Suggestion to use relevant variables names, we are not gathering mangas here :)

2024-04-15 07:36 UTC, akn19 commented
I have tried it on several titles and so far no issues have arisen.

2024-04-17 07:26 UTC, MikeZeDev commented
For the integration to work you'll also have to update your branch from our master. Github updated lint so we had to lock the version.

2024-04-24 18:09 UTC, MikeZeDev approved these changes

2024-04-24 18:09 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +                document.body.className = document.body.className.replace('darkmode', 'lightmode')
lightmode to replace darkmode? why this line? its that from elsewhere? remove it perhaps.

2024-04-24 18:09 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +        this.novelContentQuery = 'div.asdasd';
I get it. Script remove nodes matched with novelObstaclesQuery. We have legitimate text nodes <div class ="text-align"> that are removed. Suggestion to remove google ads instead : 

        this.novelObstaclesQuery = 'div[data-index]';

2024-04-24 18:09 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +                document.body.className = document.body.className.replace('darkmode', 'lightmode')
this still need to be addressed :)

2024-04-24 18:09 UTC, MikeZeDev commented on src/web/mjs/connectors/SakuraNovel.mjs
> +                document.body.className = document.body.className.replace('darkmode', 'lightmode')
@akn19 please remove the useless darkode/lightmode line and we are settled <3

2024-04-24 18:09 UTC, merged