feat(CulturedWorks): create connector
manga-download/hakuneko pull request #7057
Opened 2024-05-06 10:52 UTC by TristanWasTaken

https://culturedworks.com/

2024-05-06 13:32 UTC, MikeZeDev commented
Perhaps it time to add it to haruneko? Its not hard :)

2024-05-06 14:22 UTC, MikeZeDev requested changes

2024-05-06 14:22 UTC, MikeZeDev commented on src/web/mjs/connectors/CulturedWorks.mjs
> +export default class CulturedWorksnpm extends WordPressMangastream {
'CulturedWorksnpm' ? Should no it be 'CulturedWorks'?

2024-05-07 12:18 UTC, TristanWasTaken commented on src/web/mjs/connectors/CulturedWorks.mjs
> +export default class CulturedWorksnpm extends WordPressMangastream {
yeah, I was wondering what ate the "npm" 😅

2024-05-07 12:22 UTC, TristanWasTaken commented
> Perhaps it time to add it to haruneko? Its not hard :)

sure, but I think I already shared my disgust for some parts of the new api when I asked on Discord.
Way too much boilerplate for what could be handled by shared components, like templates in the current version.

2024-05-07 13:05 UTC, TristanWasTaken commented
> Perhaps it time to add it to haruneko? Its not hard :)

sure, but I'm not using haru as long as it's pretty much unusable
1. can't even move the window
2. forces you to read long strip/webtoon or 2 page even for single page manga
3. clunky ui
4. can't even retry downloads
5. no way to pause the download -> doesn't detect if no disk space is left
6. no way to reorder downloads or give them a priority
7. doesn't detect if chapters were already downloaded
8. local search didn't work

dev:
9. some functions are still called "mangas". The plural of manga is manga.
10. would've been nice if the dectorators, etc weren't a sub-folder of the connectors/websites folder
11. the 2 files per connector could've been moved to their own folder

and a few more that I forgot

2024-05-07 14:17 UTC, MikeZeDev commented
You do not have to use it :D.

Adding a Madara website can be done in like 10 minutes. Need file, icon and test 🤷

2024-05-07 14:31 UTC, MikeZeDev approved these changes

2024-05-08 08:19 UTC, merged