add ReadAllComics and fix ComicExtra domain
manga-download/hakuneko pull request #7074
Opened 2024-05-10 18:27 UTC by yoanhg421

Add readallcomics.com connector
Change comicextra.org to comixextra.com

2024-05-11 09:01 UTC, MikeZeDev requested changes
Fix lint errors

2024-05-11 14:09 UTC, yoanhg421 reviewed
Fixed all lint errors on latest commit

2024-05-11 16:02 UTC, MikeZeDev approved these changes
Add clipboard support and its ok.

Btw, Thanks for providing me a proper comic list, gonna add this to haruneko

2024-05-11 16:02 UTC, MikeZeDev commented on src/web/mjs/connectors/ReadAllComics.mjs
> +
One may want to implement clipboard support, since its easy 

```
import Manga from '../engine/Manga.mjs';

    async _getMangaFromURI(uri) {
        const request = new Request(uri, this.requestOptions);
        const id = uri.pathname;
        const [ title ] = await this.fetchDOM(request, 'div.description-archive h1');
        return new Manga(this, id, title.textContent.trim());
    }
```

2024-05-11 17:14 UTC, yoanhg421 commented on src/web/mjs/connectors/ReadAllComics.mjs
> +
Added the Copy Paste support and tested it.

2024-05-12 08:37 UTC, merged

2024-05-12 08:37 UTC, MikeZeDev commented
Thanks for your contribution. Now, gonna add that to haru