fix KissAway.mjs
manga-download/hakuneko pull request #7105
Opened 2024-05-25 16:48 UTC by realabertian

fix #7104

2024-05-26 09:10 UTC, MikeZeDev commented
i think there is an easier solution.

2024-05-26 09:33 UTC, MikeZeDev requested changes
Changes are not ideal and are prone to fail because of a race condition. We don't wait for the chapter/page gathering XHR request to gather the html nodes.

Solution : 

Make the request ourselves and parse the html like before. 
Random endpoints can be used, like in the Mihon extension i mentioned.

2024-05-26 09:33 UTC, MikeZeDev commented on src/web/mjs/connectors/KissAway.mjs
> +                        id : item.href,
never use full url for identifiers unless absolute necessity. But yeah, there may be a typo here

2024-06-01 00:14 UTC, realabertian commented
> Changes are not ideal and are prone to fail because of a race condition. We don't wait for the chapter/page gathering XHR request to gather the html nodes.
> 
> Solution :
> 
> Make the request ourselves and parse the html like before. Random endpoints can be used, like in the Mihon extension i mentioned.

Got it, I'll handle it

2024-06-01 10:07 UTC, MikeZeDev approved these changes

2024-06-01 10:07 UTC, merged