add connector mikoroku
manga-download/hakuneko pull request #7219
Opened 2024-06-28 18:22 UTC by akn19

2024-06-30 08:07 UTC, MikeZeDev commented
This is totally copy pasted from a single connector where i had to use hacky stuff because the website was crappy.
Not sure it is anymore. 

Was it tested? 
In case it works try to remove the hacky stuff and see if it works again. 

I ported it to Haruneko like this, maybe you can find some inspiration here : https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/NextScan.ts ?

2024-07-03 14:01 UTC, akn19 commented
I've cleaned up the code. The code has been tested on several titles and there are no issues.

2024-07-03 16:32 UTC, MikeZeDev requested changes
Perhaps _getChapters can be simplified?

2024-07-03 16:32 UTC, MikeZeDev commented on src/web/mjs/connectors/Mikoroku.mjs
> +        if (clwdrun.length > 0) {
Do we really need to check for 'clwd.run' AND div#epx? 

Isn't the check for " 'clwd.run'" enough? Thats waht i was implying when i said "simplify the script"

Edit : apparently `clwd` variable contains chapters list, perhaps its easier to exploit this by injecting a script (using this.fetchUI? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/8f766a3d-4ce6-4b19-a0c8-8af14c24e26b)

2024-07-26 13:10 UTC, ronny1982 commented
Suggestion to close PR after **Friday, 20 September 2024** (12 weeks) if not approved by a reviewer.

2024-07-30 12:19 UTC, akn19 commented on src/web/mjs/connectors/Mikoroku.mjs
> +        if (clwdrun.length > 0) {
done

2024-07-31 17:21 UTC, MikeZeDev approved these changes

2024-07-31 17:22 UTC, merged