CuuTruyen
manga-download/hakuneko pull request #7307
Opened 2024-08-05 03:53 UTC by beer-psi

Take two, with 100% less WASM blob now that I figured the descrambling mechanism.

2024-08-05 16:00 UTC, MikeZeDev requested changes
Minor changes requested.

Btw, nice work figuring out the image encryption.

2024-08-05 16:00 UTC, MikeZeDev commented on src/web/mjs/connectors/CuuTruyen.mjs
> +        const data = await this.fetchJSON(request);
Since we only use the name from the api, perhaps we can directly affect it? 

```
        const { data : {name } } = await this.fetchJSON(request);
        return new Manga(this, mangaid, name.trim());
```

2024-08-05 16:00 UTC, MikeZeDev commented on src/web/mjs/connectors/CuuTruyen.mjs
> +        const uri = new URL('/api/v2/mangas/' + manga.id + '/chapters', this.url);
For consistency sake, maybe we could use interpolation on every requests? 

const uri = new URL(\`/api/v2/mangas/${manga.id}/chapters\`, this.url);

2024-08-05 16:00 UTC, MikeZeDev commented on src/web/mjs/connectors/CuuTruyen.mjs
> +            .filter((c) => c.status === 'processed')
Please avoid shortening variable names. 'chapter' is fine .
I suppose data.data is an array of chapter, just do  const { data } then return data.filter ....

2024-08-05 16:00 UTC, MikeZeDev commented on src/web/mjs/connectors/CuuTruyen.mjs
> +        const data = await this.fetchJSON(request);
If we are just using pages, we may as well do 

`        const { data : { pages }} = await this.fetchJSON(request);`

You can chain .filter and .map after

```
        return pages
            .filter(filter((image) => image.status === 'processed')
            .map((image) => {

```

2024-08-05 16:00 UTC, MikeZeDev commented on src/web/mjs/connectors/CuuTruyen.mjs
> +        const resp = await fetch(payload.url, {
resp is a bit short, response is fine.

2024-08-05 16:00 UTC, MikeZeDev commented on src/web/mjs/connectors/CuuTruyen.mjs
> +            credentials: 'same-origin',
Are those parameters necessary? fetch default behavior is follow, and ive tested without it, without credentials cache and changing accept. Its still working. 

Perhaps just the referrer is enough, and just one. 
X-referrer is useless in the fetch context and is used when we use Request iirc

2024-08-05 16:00 UTC, MikeZeDev commented on src/web/mjs/connectors/CuuTruyen.mjs
> +        const pages = data.data.pages.filter((image) => image.status === 'processed');
Is there a need to filter here ? Because of the previous check, wont the image all be 'processed' ?

2024-08-05 16:10 UTC, MikeZeDev commented on src/web/mjs/connectors/CuuTruyen.mjs
> +            const mangas = await this._getMangasFromPage(data);
_getMangasFromPage is not async, i guess there is no need for await.

2024-08-06 07:08 UTC, MikeZeDev approved these changes

2024-08-06 07:08 UTC, merged

2024-11-01 02:30 UTC, TraLeeee commented
@beer-psi Sorry for asking this silly question?! But how you know the key is "_3141592653589793_" to decode the xor cipher? How can i find this key?