feat(Iken, VortexScans, MangaGalaxy): add Iken template
manga-download/hakuneko pull request #7462
Opened 2024-10-06 03:14 UTC by TristanWasTaken

https://vortexscans.org
https://mangagalaxy.net

source: [keiyoushi](https://github.com/keiyoushi/extensions-source/tree/ac045e662ea970d23bf77d8320542ed5e0af8462/lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken)

resolves #7250 
resolves #7277

2024-10-06 08:36 UTC, MikeZeDev requested changes

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/Vortex_Scans.mjs
> +        super.id = 'vortex_scans';
Since the old VortexScans is long dead you can reuse the name and id, i did the same.
Just modify the old file and update the icon.

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        this.path = '/api/query';
As you will find later, it would be better to leave the api path as '/api/' , perhaps

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        let mangaList = [];
use const

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +            let list = await this._getMangasFromPage(page);
use const. Adding or removing element in an array will still work.

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        let chapterList = [];
use const

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +            let list = await this._getChaptersFromPage(manga.id, page);
use const

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        this.api = undefined;
Why this.api and this.path ? Especially when you dont define path in the two connectors 🤷 

Perhaps you wants to have a look into

https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/VortexScans.ts
https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/MangaGalaxy.ts

?

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +
Looping from all mangas is inneficient and ugly.

Look how its done in Haruneko

https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/VortexScans.ts#L53

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        const request = new Request(new URL(`${this.path}?page=${page}&perPage=1000`, this.api), this.requestOptions);
Remove useless function

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +import Manga from '../../engine/Manga.mjs';
Perhaps name it Iken.mjs instead of iken.mjs?

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        const request = new Request(new URL(`${this.path}?page=${page}&perPage=1000`, this.api), this.requestOptions);
Personal taste : i kept it at 200 in Haruneko but its up to you.

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        const script = `
I assume this is for getting the pictures after page js did the work. Shouldnt we put a delay before actually gathering the pages? 

```js
        const script = `
            new Promise((resolve, reject) => {
                setTimeout(() => {
                    try {
                        resolve ([...document.querySelectorAll('${this.queryPages}')].map(images.map(image => image.src)));
                    } catch(error) {
                        reject(error);
                    }
                }, 2500);
            });
        `;
```

2024-10-06 08:36 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        const script = `
Btw, if you dont do any async work in the promise, no need to wrap in into a try catch, its defeating the purpose of the promise as any error reject it.

```js
            new Promise( resolve => {
                    const images = [...document.querySelectorAll('${this.queryPages}')];
                    resolve(images.map(image => image.src));
            });
```

try catch is necessary on async promises or with a delay, like if you use settimeout / setinterval.

```js
    new Promise( (resolve, reject) => {
        const interval = setInterval(function () {
            try {
                if (document.querySelector('#idIframe')) {
                    clearInterval(interval);
                    resolve(document.querySelector('#idIframe').src);
                }
            } catch (error) {
                clearInterval(interval);
                reject(error);
            }
        }, 1000);
    })
```

2024-10-06 13:47 UTC, TristanWasTaken commented on src/web/mjs/connectors/templates/iken.mjs
> +            let list = await this._getMangasFromPage(page);
wait wtf I didn't know that
yet again a cursed js moment

2024-10-06 13:48 UTC, TristanWasTaken commented on src/web/mjs/connectors/templates/iken.mjs
> +        const request = new Request(new URL(`${this.path}?page=${page}&perPage=1000`, this.api), this.requestOptions);
I took the 1k from the mihon extension

2024-10-06 14:04 UTC, TristanWasTaken commented on src/web/mjs/connectors/templates/iken.mjs
> +        const script = `
> I assume this is for getting the pictures after page js did the work. Shouldnt we put a delay before actually gathering the pages?

Yes. It should be fine since nextjs responds with the images in the first request. When I wrote this, I saw no reason to artificially prolong a download.
Should I still add a delay just to be safe?

2024-10-06 14:05 UTC, TristanWasTaken commented on src/web/mjs/connectors/templates/iken.mjs
> +        this.api = undefined;
I was planning to use this to make it easier in case they split off the api, but then I just completely forgot 😅

2024-10-07 09:26 UTC, MikeZeDev requested changes

2024-10-07 09:26 UTC, MikeZeDev commented on src/web/mjs/connectors/Vortex-Scans.mjs
> +import FoolSlide from './templates/FoolSlide.mjs';
Remove this file and the matching icon

2024-10-07 09:26 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/Iken.mjs
> +        this.api = undefined;
this.api is never used.

2024-10-07 09:26 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/Iken.mjs
> +        this.path = '/api';
perhaps name it apiPath to give the name more meaning ?

2024-10-07 09:27 UTC, MikeZeDev commented on src/web/mjs/connectors/templates/iken.mjs
> +        const script = `
Yeah, better safe than sorry

2024-10-08 20:43 UTC, TristanWasTaken commented on src/web/mjs/connectors/templates/iken.mjs
> +        const script = `
> Yeah, better safe than sorry. 

aight

> Haruneko got an integrated delay mechanism when injecting JS btw.

yeah I still won't bother with it until it is as convenient as haku 😅

2024-10-09 15:40 UTC, MikeZeDev approved these changes

2024-10-09 15:42 UTC, merged