Add CoroCoro connector
manga-download/hakuneko pull request #7472
Opened 2024-10-10 11:33 UTC by viliml

2024-10-10 19:08 UTC, MikeZeDev requested changes
Nice work but

* Dont assume the script you want is the nth script in all the page scripts. Perform checks on the script content instead.

* I dont like those eval at all. If you want to use eval perhaps you should use them in browser context i.e injecting a script using `Engine.Request.fetchUI`. Perhaps is event easier this way, if you are able to parse next_f array idk.

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        if (uri.pathname.startsWith('/chapter/')) {
People shouldnt not paste chapter link. remove this

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +            const data = await this.fetchDOM(uri, 'h1');
using h1 as CSS selector is prone to errors. Use a more refined selector.

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        const script = scripts[scripts.length - 2].innerText;
script order is unreliable to gather the good one. Use another method.

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        const script = scripts[scripts.length - 3].innerText;
script order is unreliable to gather the good one. Use another method.

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        const script = scripts[scripts.length - 1].innerText;
script order is unreliable to gather the good one. Use another method.

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        const mimeType = 'image/' + (ext === 'jpg' ? 'jpeg' : ext);
no need for mimeType if we use _applyRealMime

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        const ext = payload.src.substring(payload.src.lastIndexOf('.', payload.src.indexOf('.enc') - 1) + 1, payload.src.indexOf('.enc'));
Perhaps a regexp would be more readable to extract the extension?

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +            const id = uri.pathname.substring('/title/'.length);
wouldnt it be better to use uri.pathname.split('/').at() ?

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +const weekdays = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
Should be moved in the function who need it tbh( see your _getChapters)

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        if (uri.pathname.startsWith('/title/')) {
If you really wants to make sure people paste manga link,  override canHandleUri

```js
    canHandleURI(uri) {
        return /https?:\/\/(?:www\.)?template.net/.test(uri.origin);
    }
```

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        const json = eval(script.substring(22, script.length - 2));
not fond of evaluating code from website directly inside our code, for security reasons.

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        const json = eval(script.substring(22, script.length - 2));
not fond of evaluating code from website directly inside our code, for security reasons.

2024-10-10 19:08 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        const json = eval(script.substring(22, script.length - 2));
not fond of evaluating code from website directly inside our code, for security reasons.

2024-10-12 07:41 UTC, MikeZeDev requested changes

2024-10-12 07:41 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +        for (const scriptElem of scripts.reverse()) {
No need to loop by yourself if you can identify the script by content
```js
const scripts = [...document.querySelectorAll('script')];
const script = scripts.find(script=> script.innerText.indexOf('totalChapterLikes') > 0)?.innerText;
const json = JSON.parse(script.substring(22, script.length - 2));
const data = JSON.parse(json.substring(json.indexOf(':') + 1))[3]['children'][3]['weekdays'];
```

2024-10-12 07:41 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +                const data = JSON.parse(json.substring(json.indexOf(':') + 1))[3]['children'][0][3]['children'][1][3]['section']['chapters'];
hum... Thats a lot of fixed indexes :/
Since the position of "chapters" in the json object may vary, why not trying to locate it dynamically? 

```js

function locate(obj, keyname)
  {
    if (!obj) return null;
    if (obj[keyname]) {
      return (obj[keyname]);
    }
    
   let result = null;
 
    for (i in obj) {
      if (typeof obj[i] === 'object')
       result = result ?? locate(obj[i], keyname);
    }
    return result;

  }

const scripts = [...document.querySelectorAll('script')];
const script = scripts.find(script=> script.innerText.indexOf('omittedMiddleChapters') > 0)?.innerText;
const json = JSON.parse(script.substring(22, script.length - 2));
const data = JSON.parse(json.substring(json.indexOf(':') + 1));
 const chapters = locate(data, 'chapters');
```

Or if you fear that "chapters" wont be unique you may want to "locate" 'earlyChapters', 'omittedMiddleChapters' and 'latestChapters'. I doubt there will be duplicates.

And maybe, do that for the other JSON parsing, idk?

2024-10-12 07:41 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +                const json = JSON.parse(script.substring(22, script.length - 2));
Proposition  : 

```js 

function locate(obj, keyname)
  {
    if (!obj) return null;
    if (obj[keyname]) {
      return (obj[keyname]);
    }
    
   let result = null;
 
    for (i in obj) {
      if (typeof obj[i] === 'object')
       result = result ?? locate(obj[i], keyname);
    }
    return result;

  }

const scripts = [...document.querySelectorAll('script')];
const script = scripts.find(script=> script.innerText.indexOf('viewerSection') > 0)?.innerText;
const json = JSON.parse(script.substring(22, script.length - 2));
const data = JSON.parse(json.substring(json.indexOf(':') + 1));
const pages = locate(data, 'viewerSection')?.pages;
```

2024-10-12 07:41 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +                const json = JSON.parse(script.substring(22, script.length - 2));
BTW, since JSON parsing first steps are the same perhaps we should make a function? 

```js

function findAndParseJSON(scripts, textToFind) {
  const script = scripts.find(script=> script.innerText.indexOf(textToFind) > 0)?.innerText;
  const json = JSON.parse(script.substring(22, script.length - 2));
  return JSON.parse(json.substring(json.indexOf(':') + 1))
}

const scripts = [...document.querySelectorAll('script')];
const data = findAndParseJSON( scripts, 'weekdays');

```

2024-10-12 11:29 UTC, viliml commented
The "allow edits by maintainers" checkbox is checked, since you're already writing full snippets of fixed code in your comments you might as well commit them.

2024-10-17 07:40 UTC, MikeZeDev commented
I have no time to spare and no intention to add such complex website to Hakuneko anymore. Its better for the team and for everyone to spend time on Haruneko where this website was added and working until its last update.

2024-10-25 20:59 UTC, ronny1982 commented
Suggestion to close PR after **Thursday, 2 January 2025** (12 weeks) if not approved by a reviewer.

2024-12-12 09:22 UTC, MikeZeDev commented
Ooooh, they use protobuff now? awesome, gotta review that asap <3

2024-12-12 10:02 UTC, MikeZeDev requested changes
Nice work with the prototypes.
Some things still must be changed tho.

2024-12-12 10:02 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +     * @param {URL} uri
Comment should be removed as its content can easily be inferred from the code.

2024-12-12 10:02 UTC, MikeZeDev commented on src/web/mjs/connectors/CoroCoro.mjs
> +     * @param {URL} uri
same everywhere else

2024-12-13 15:05 UTC, MikeZeDev commented
Hey, they just added a new endpoint for rensai ! you can get rid of all those JSON parsing !

![image](https://github.com/user-attachments/assets/529309d0-a17c-4dd2-a6dc-d4cef5ad39fe)

2025-01-07 18:39 UTC, ronny1982 commented
Closed => long lasting PR, feel free to re-open

2025-01-07 18:39 UTC, closed without merging